Rebuild run graph after transform jobs
awslabs/aws-build-accumulator pull request #126
Opened 2022-03-07 21:34 UTC by nrdg42

Transform jobs will only output dicts with keys that are command-line
switches. After receiving new user jobs, Litani will discard the
previous run graph and build a new one

This fixes #105

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-03-08 20:54 UTC, karkhaz requested changes
Looking forward to this!

2022-03-08 20:54 UTC, karkhaz commented on lib/add_job.py
> +import json
License header please

2022-03-08 20:54 UTC, karkhaz commented on lib/add_job.py
> +async def add_job(job_dict):
This seems like it's been moved without modifications, could it be a different commit?

2022-03-08 20:54 UTC, karkhaz commented on lib/transform_jobs.py
> +            logging.info("Discarding job %s", job_file.name)
Since we're always discarding all old jobs, I no longer think this message needs to be here, it's not that helpful.

2022-03-08 20:54 UTC, karkhaz commented on lib/transform_jobs.py
> +                logging.error("Unable to delete %s", job_file.name)
Again, I think this is no longer notable, no need to log.

2022-03-08 20:54 UTC, karkhaz commented on lib/transform_jobs.py
> +            for key in ("job_id", "status_file", "subcommand"):
You're not adding `"subcommand"` back in when you restore the jobs, it looks like

2022-03-09 14:31 UTC, nrdg42 commented on lib/transform_jobs.py
> +            for key in ("job_id", "status_file", "subcommand"):
Do we use the `subcommand` key? Should it be the same as it was before transform jobs or should it be set to `transform-jobs`?

2022-03-10 00:43 UTC, angelonakos commented on lib/transform_jobs.py
> +            for key in ("job_id", "status_file", "subcommand"):
> Do we use the subcommand key? 

Not sure. I haven't checked.

> Should it be the same as it was before transform jobs or should it be set to transform-jobs?

I would prefer if it is set to `transform-jobs` to reflect the fact that the subcommand has changed.

2022-03-10 00:52 UTC, karkhaz approved these changes

2022-03-10 15:46 UTC, angelonakos approved these changes

2022-03-11 14:26 UTC, closed without merging