Fix get-jobs man page
awslabs/aws-build-accumulator pull request #138
Opened 2022-04-02 20:51 UTC by ronakfof

*Issue #, if available:*

*Description of changes:*
Previously in `litani get-jobs` man page, line 55 was starting with
```
`set-jobs`
```
which failed doc creation with the following error - 
```
[1/4] converting litani-get-jobs to man
FAILED: /Users/ronakf/Desktop/aws-build-accumulator/doc/out/man/litani-get-jobs.1 
scdoc < /Users/ronakf/Desktop/aws-build-accumulator/doc/src/man/litani-get-jobs.scdoc > /Users/ronakf/Desktop/aws-build-accumulator/doc/out/man/litani-get-jobs.1
Error at 55:2: Expected ``` and a newline to begin literal block
ninja: build stopped: subcommand failed.
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-02 21:19 UTC, angelonakos approved these changes

2022-04-04 14:08 UTC, karkhaz approved these changes

2022-04-04 14:20 UTC, karkhaz requested changes
The actual fix is to use `*` rather than \`.

2022-04-04 19:08 UTC, karkhaz approved these changes

2022-04-04 19:09 UTC, merged