Create deb package on pr
awslabs/aws-build-accumulator pull request #139
Opened 2022-04-04 14:52 UTC by ronakfof

*Issue #, if available:*

*Description of changes:*
With this change, now a deb package can be created and upload to artifacts for Pull Requests labeled with `create-deb-package`

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-04 20:44 UTC, nrdg42 commented
What's the use case of this feature?

2022-04-05 00:50 UTC, angelonakos commented
> What's the use case of this feature?

This "create-deb-package" label enables downstream customers of Litani to create experimental packages and to test out these types of packages with regards to their use case without our team having to merge a change or cut a release.

2022-04-06 19:03 UTC, angelonakos approved these changes

2022-04-06 20:40 UTC, karkhaz requested changes
Nice, thank you, it's good to see it split into several files also. Does anything depend on the `release-packages.yaml` that was renamed to `actions/build/action.yaml`?

2022-04-06 20:40 UTC, karkhaz commented on .github/actions/build/action.yaml
> +        Description: A program that provides platform-independent job control.
Could you use the latest text from the README?

2022-04-07 12:58 UTC, ronakfof commented
> Nice, thank you, it's good to see it split into several files also. Does anything depend on the `release-packages.yaml` that was renamed to `actions/build/action.yaml`?

`release-packages.yaml` is deleted. I separated both `release brew` and `release deb` process into 2 separate workflows. And since creation of deb package was being done in 2 workflows (release and on pr), I abstracted it into `actions/build/action.yaml`. So both `release-deb.yaml` and `create-deb-on-pr.yaml` depend on it now

2022-04-07 13:06 UTC, ronakfof commented on .github/actions/build/action.yaml
> +        Description: A program that provides platform-independent job control.
Resolved

2022-04-08 19:57 UTC, karkhaz approved these changes

2022-04-08 20:30 UTC, merged