Summarize build results by printing a JSON object
awslabs/aws-build-accumulator pull request #167
Opened 2022-05-24 11:21 UTC by angelonakos

*Issue #, if available:*

*Description of changes:*

A flag was added to `run-build` that summarizes the results of a build by printing a JSON object.
    
A user will be able to get a breakdown of statuses across pipelines as well as a breakdown of the
status of each pipeline.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-05-24 14:54 UTC, karkhaz requested changes
I don't think this application-level reporting belongs here. Different users of Litani would want different kinds of reports, and I wouldn't want to bake this particular JSON report into the CL interface... once it's in, we can't change it, even if somebody wants something slightly different.

I think applications should just run `dump-run` or `get-jobs` (preferably the latter) and use that for whatever output they want.

2022-05-24 14:54 UTC, karkhaz commented on lib/post_build.py
> +        if status_name_pretty not in status_summary_map:
```
try:
  status_summary_map[status_name_pretty] += 1
except KeyError:
    status_summary_map[status_name_pretty] = 1

2022-05-25 13:20 UTC, angelonakos commented on lib/post_build.py
> +        if status_name_pretty not in status_summary_map:
Done

2022-05-25 13:29 UTC, angelonakos commented
Canceling

2022-05-25 13:29 UTC, closed without merging