Adding a line break after a specific truncate length
awslabs/aws-build-accumulator pull request #53
Opened 2021-10-07 20:34 UTC by ronakfof

*Issue #, if available:*
https://github.com/awslabs/aws-build-accumulator/issues/45

*Description of changes:*
Adding a line break after a specified truncate length

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-10-07 21:04 UTC, angelonakos requested changes
I ran this locally and long labels were wrapped appropriately.

However, I suggest create a function such as the one below and reusing appropriately:

```python
def wrap_command(command, limit):
    occurrences = re.findall('.{1,%i}' % limit, command)
    newline_separated_command = '\n'.join(occurrences)
    return newline_separated_command
    
```

2021-10-07 21:04 UTC, angelonakos commented on lib/graph.py
> +                re.findall('.{1,%i}' % truncate, command)
Why are you using `truncate` and not `truncate-1` in the modulo operation?

Meaning, why are you using:

```python
re.findall('.{1,%i}' % truncate, command)
```

instead of:


```python
re.findall('.{1,%i}' % (truncate-1), command)
```

2021-10-08 00:45 UTC, angelonakos approved these changes

2021-10-08 22:32 UTC, ronakfof commented
Closing this one as the issue will be resolved with this [PR](https://github.com/awslabs/aws-build-accumulator/pull/56).

2021-10-08 22:32 UTC, closed without merging