Show running jobs on pipeline page
awslabs/aws-build-accumulator pull request #71
Opened 2022-01-05 19:59 UTC by nrdg42

Distinguish the jobs that are currently running from the jobs that have
not started on the pipeline HTML page. Use CSS to color jobs that are
currently running orange on the dependency graph, border them in orange
on the pipeline page, and only show the in progress icon on running jobs
in the table of contents.

![image](https://user-images.githubusercontent.com/68433946/148280892-65e2a14d-c956-44d5-9e1f-35b5fa189280.png)

![image](https://user-images.githubusercontent.com/68433946/148280947-93815dde-081d-4aa7-bcff-dba5a74195d1.png)

*Issue #, if available:*
#67  

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-05 21:46 UTC, angelonakos approved these changes

2022-01-05 22:40 UTC, karkhaz requested changes
This is great, thank you!

I think the orange is too close to the colour we use for `fail_ignored`, which is also orange rather than red. Can I suggest to give the div a black border for running? I think that still distinguishes it reasonably well from not-started, which has an invisible border.

For the dependency graph, I suggest white node with black text for running, and white node with grey text for not started.

2022-01-06 15:25 UTC, feliperodri commented
@nrdg42 That's great!! Thanks for implementing this change. I agree with Kareem about the color pattern. We should try to use distinct and intuitive colors, but most important we need a **legend color**! New users need a straightforward way to know what each color represent.

2022-01-06 21:34 UTC, nrdg42 commented
How about something like this for now? I see the need for a Legend like @feliperodri says.


<img width="979" alt="image" src="https://user-images.githubusercontent.com/68433946/148455164-3cc59568-eda4-4f6c-b506-83bc2f93ef06.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/68433946/148455184-c5c5c2f0-9a1b-4462-b707-b91d30a44dcb.png">

2022-01-07 15:00 UTC, karkhaz approved these changes

2022-01-07 15:02 UTC, karkhaz commented
That's a good idea @feliperodri ... that should be reasonably easy to do, let's merge this and we'll put the legend on the backlog, shouldn't take too long.

2022-01-07 17:54 UTC, feliperodri approved these changes

2022-01-10 15:06 UTC, merged