Sort pipelines by status and then name
awslabs/aws-build-accumulator pull request #97
Opened 2022-02-10 21:49 UTC by angelonakos

*Issue #, if available:*

*Description of changes:*

Name will now be used as the second criterion when sorting pipelines.

The order with which pipelines appear in both the HTML dashboard is the same as
the order with which they appear in the run.json. An e2e test was added to 
ensure that the order is indeed the intended one.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-11 14:28 UTC, karkhaz requested changes

2022-02-11 14:28 UTC, karkhaz commented on test/e2e/tests/pipeline_order.py
> +    for element in (
`for ci_stage, pipeline in(`

2022-02-11 14:28 UTC, karkhaz commented on test/e2e/tests/pipeline_order.py
> +        for idx, stage_obj in enumerate(run["pipelines"][index]["ci_stages"]):
The rest of this method (from this line down) seems like it's testing something different, though I'm not completely certain because it's also very complicated... it seems like two tests in one? And I'm not really sure that testing that the CI stages are in the right order is necessary, since you've given all the pipelines unique names, so just checking that the names are sorted should be enough?

I don't understand why this test isn't just something like
```
return [p["name" for p in run["pipelines"]] == [
            "zeta", "0", "00", "01", "1", "Beta", "alpha", "beta", "beta1",
            "beta2", "betaa", "delta", "epsilon", "gamma",
]
```

2022-02-11 15:11 UTC, angelonakos commented on test/e2e/tests/pipeline_order.py
> +        for idx, stage_obj in enumerate(run["pipelines"][index]["ci_stages"]):
Indeed this is much simpler. I was unnecessarily complicating this test. Checking the order of names alone will suffice

2022-02-11 21:11 UTC, karkhaz approved these changes

2022-02-14 07:51 UTC, ronakfof approved these changes

2022-02-14 13:19 UTC, merged